### ISSUE TITLE
Yield * support

### ISSUE THREAD

**Issue by jplorandi** [ericelliott/asyncfunc#7]
I have a hierarchical structure in a Mongo database that I'm accessing thru Mongoose. Each record has an optional field `next`, which has the ObjectId of the next node in the chain, if applicable. I'm trying to use ogen to ascertain this chain does not loop back onto itself, with the following code:

``` javascript

function* getNext(from, count) {
  let record = yield Node.findById(from).exec();
  console.log('record: ', record);
  if (record.next && count < 16)
    yield * getNext(record.next, count + 1);

  return;
}

const findNext = ogen(getNext);

function loopsBack(to, from, callback) {
  let gen = findNext(to, 0);

  const subs = gen.subscribe(
    (current) => { console.log('g: ', current); callback(true) },
    (error) => callback(false),
    () => callback(false)
  );

  subs.dispose();
}

```

The code works correctly until it finds a record without a `next` field (or where the field is null), whereby it hangs. Any ideas?

**Comment by ericelliott** [comment]
Can you reproduce the issue with no external dependencies?

**Comment by jplorandi** [comment]
Eric, the problem lies in `subs.dispose()`. Essentially, I was calling that method before the subscription ran its course. moving that line into the `onComplete` callback fixed the issue. Perhaps it's worth mentioning on the README?

**Comment by ericelliott** [comment]
Oops! This probably shouldn't be called out explicitly in this README, because that has more to do with just using observables correctly -- but we probably should link to RxJS docs. =)

Glad you figured it out!  👍
